--CREATE TABLES
CREATE TABLE CLIENTS (
  ID NUMERIC(10) PRIMARY KEY,
  NAME VARCHAR(1000),
  PLACE_OF_BIRTH VARCHAR(1000),
  DATE_OF_BIRTH DATE,
  ADDRESS VARCHAR(1000),
  PASSPORT VARCHAR(100)
);

CREATE TABLE PRODUCTS (
  ID NUMERIC(10) PRIMARY KEY,
  PRODUCT_TYPE_ID NUMERIC(10) NOT NULL,
  NAME VARCHAR(100),
  CLIENT_REF NUMERIC(10) NOT NULL,
  OPEN_DATE DATE,
  CLOSE_DATE DATE,
);

CREATE TABLE PRODUCT_TYPE (
  ID NUMERIC(10) PRIMARY KEY,
  NAME VARCHAR(100),
  BEGIN_DATE DATE,
  END_DATE DATE,
  TARIF_REF NUMERIC(10) NOT NULL,
);

CREATE TABLE ACCOUNTS (
  ID NUMERIC(10) PRIMARY KEY,
  NAME VARCHAR(100),
  SALDO NUMERIC(10,2),
  CLIENT_REF NUMERIC(10) NOT NULL,
  OPEN_DATE DATE,
  CLOSE_DATE DATE,
  PRODUCT_REF NUMERIC(10) NOT NULL,
  ACC_NUM VARCHAR(25),
);

CREATE TABLE RECORDS (
  ID NUMERIC(10) PRIMARY KEY,
  DT NUMERIC(1),
  SUM NUMERIC(10,2),
  ACC_REF NUMERIC(10) NOT NULL,
  OPEN_DATE DATE
);

CREATE TABLE TARIFS (
  ID NUMERIC(10) PRIMARY KEY,
  NAME VARCHAR(100),
  COST NUMERIC(10,2)
);

--CREATE CONSTRAINTS

ALTER TABLE PRODUCTS
  ADD
    CONSTRAINT PROD_CL_FK
    FOREIGN KEY (CLIENT_REF)
    REFERENCES CLIENTS (ID),
    CONSTRAINT PROD_PRODTYPE_FK
    FOREIGN KEY (PRODUCT_TYPE_ID)
    REFERENCES PRODUCT_TYPE (ID);

ALTER TABLE PRODUCT_TYPE
  ADD
    CONSTRAINT PROD_TYPE_TAR_FK
    FOREIGN KEY (TARIF_REF)
    REFERENCES TARIFS (ID);

ALTER TABLE ACCOUNTS
  ADD
    CONSTRAINT ACC_CL_FK
    FOREIGN KEY (CLIENT_REF)
    REFERENCES CLIENTS (ID),
    CONSTRAINT ACC_PROD_FK
    FOREIGN KEY (PRODUCT_REF)
    REFERENCES PRODUCTS (ID);

ALTER TABLE RECORDS
  ADD
    CONSTRAINT REC_ACC_FK
    FOREIGN KEY (ACC_REF)
    REFERENCES ACCOUNTS (ID);